# Generated by Django 5.2.12 on 2026-03-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='projects_images/')),
                ('description_es', models.TextField(default='Translated text', verbose_name='Spanish description')),
                ('description_en', models.TextField(default='Translated text', verbose_name='English description')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('deploy_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dev', 'Development'), ('done', 'Completed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myprojects.project')),
            ],
        ),
    ]
